Improve process shutdown handling
Graylog2/collector-sidecar pull request #462
Opened 2023-01-03 10:29 UTC by mpfz0r

If killing just the forked PID is not working,
try to kill the entire process group.

This should help in scenarios where a wrapper script is used, which doesn't pass the signal to all of it's children.

## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

2023-01-04 15:27 UTC, danotorrey commented
Fixes #463

2023-01-06 14:10 UTC, thll requested changes
Nice improvement! Worked as expected in my tests.

I left some comments which are up for discussion.

2023-01-09 08:16 UTC, mpfz0r commented on daemon/exec_runner.go
> +	KillProcess(r, r.cmd.Process)
yeah, makes sense :+1:

2023-01-09 09:05 UTC, bernd reviewed
We should make the process and sidecar timeouts configurable to let users adjust them if they have processes that shut down slowly.

2023-01-09 11:31 UTC, mpfz0r commented
@bernd  @thll  I think I've addressed all your comments. Thank you :+1:

2023-01-09 13:43 UTC, thll approved these changes
Looks good to me and works well 👍

2023-01-11 15:17 UTC, bernd approved these changes

2023-01-12 12:51 UTC, merged